### ISSUE TITLE
Swift3 support

### ISSUE THREAD

**Issue by tosslife** [casbeebc/TouchMenu#1]
can you update to  swift 3.0 support! tks

**Comment by casbeebc** [comment]
**Upgraded to Swift 3.x**

Sorry for the wait. I actually just noticed your issue this week. I did not think anyone would care about this little thing, no notifications.

Fixed https://github.com/casbeebc/TouchMenu/commit/36cc5709e616844e23b8bbfebc77aa6aa0dfe3fd
